# Owner-authorized source-specific policy. No dependency source is rewritten.
if(NOT PROJECT_NAME STREQUAL "AzerothCore" OR NOT CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
  message(FATAL_ERROR "Forge warning policy requires AzerothCore with Clang")
endif()
if(NOT EXISTS "${FORGE_UPSTREAM_INVENTORY}")
  message(FATAL_ERROR "Protected verified upstream inventory is required")
endif()
get_property(_forge_scheduled GLOBAL PROPERTY FORGE_UPSTREAM_SCHEDULED)
if(_forge_scheduled)
  message(FATAL_ERROR "Forge warning policy hook must run once")
endif()
file(READ "${FORGE_UPSTREAM_INVENTORY}" _forge_inventory)
set_property(GLOBAL PROPERTY FORGE_UPSTREAM_SCHEDULED TRUE)
set_property(GLOBAL PROPERTY FORGE_UPSTREAM_INVENTORY "${_forge_inventory}")
add_compile_options(-Xclang -fno-diagnostics-use-presumed-location -fdiagnostics-absolute-paths
  -fmacro-backtrace-limit=0 -ftemplate-backtrace-limit=0)

function(forge_apply_upstream_directory _directory)
  get_property(_inventory GLOBAL PROPERTY FORGE_UPSTREAM_INVENTORY)
  get_property(_targets DIRECTORY "${_directory}" PROPERTY BUILDSYSTEM_TARGETS)
  foreach(_target IN LISTS _targets)
    get_target_property(_sources "${_target}" SOURCES)
    get_target_property(_source_dir "${_target}" SOURCE_DIR)
    foreach(_source IN LISTS _sources)
      if(_source MATCHES "\\$<")
        continue() # Generated/opaque sources keep -Werror; command verification is mandatory.
      endif()
      cmake_path(ABSOLUTE_PATH _source BASE_DIRECTORY "${_source_dir}" NORMALIZE OUTPUT_VARIABLE _absolute)
      string(JSON _expected ERROR_VARIABLE _missing GET "${_inventory}" files "${_absolute}" sha256)
      if(NOT _missing)
        if(NOT EXISTS "${_absolute}" OR IS_SYMLINK "${_absolute}")
          message(FATAL_ERROR "Verified upstream source disappeared or became a symlink")
        endif()
        file(SHA256 "${_absolute}" _actual)
        if(NOT _actual STREQUAL _expected)
          message(FATAL_ERROR "Verified upstream source changed before generation")
        endif()
        # SOURCE properties are directory-scoped; never demote the combined modules target.
        get_source_file_property(_options "${_absolute}" DIRECTORY "${_source_dir}" COMPILE_OPTIONS)
        if(NOT "-Wno-error" IN_LIST _options)
          set_property(SOURCE "${_absolute}" DIRECTORY "${_source_dir}" APPEND PROPERTY COMPILE_OPTIONS "-Wno-error")
        endif()
      endif()
    endforeach()
  endforeach()
  get_property(_children DIRECTORY "${_directory}" PROPERTY SUBDIRECTORIES)
  foreach(_child IN LISTS _children)
    forge_apply_upstream_directory("${_child}")
  endforeach()
endfunction()

function(forge_apply_upstream_policy)
  forge_apply_upstream_directory("${CMAKE_SOURCE_DIR}")
  message(STATUS "OWNER-AUTHORIZED upstream warnings: verified source scope; full provenance check required")
endfunction()
cmake_language(DEFER CALL forge_apply_upstream_policy)
